### ISSUE TITLE
`open` command doesn't work in tmux on OSX

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#120]
Error message:
```
The window server could not be contacted.  open must be run with a user logged in at the console, either as that user or as root.
```
Possible fix: https://www.elmund.io/osx/2015/07/10/open-command-in-osx-tmux/

I don't want the fix to this problem to make it so that `reattach-to-user-namespace` flashes briefly as the name of newly created tmux windows, though, like it did in [rally-emacs](https://github.com/RallySoftware/rally-emacs).

**Comment by raxod502** [comment]
Unfortunately, this bug also renders [`incanter`](https://github.com/incanter/incanter) incapable of rendering graphs from the REPL. Steps to reproduce:
```
$ lein with-profile +inject,+alembic repl
user=> (./distill '[incanter "1.5.7"])
user=> (use '(incanter core stats charts io))
user=> (view (histogram (sample-normal 1000)))
```
The last command will produce a graph in a separate window if and only if you are **not** inside tmux.

**Comment by raxod502** [comment]
This also prevents Geiser's documentation lookup, since it requires opening an HTML webpage using AppleScript.

**Comment by raxod502** [comment]
This breaks `texdoc`, since it relies on `open`.

**Comment by flaugher** [comment]
Was this issue ever resolved?  It's very annoying.  Thanks.

**Comment by raxod502** [comment]
@flaugher It should have been fixed in https://github.com/raxod502/radian/commit/b1d9c93b7d5cd45fed3982135e9b73b9432ba0a6 (which has been updated a number of times since then). If it's not working for you, make sure you have done `brew install reattach-to-user-namespace`.
