### ISSUE TITLE
Is turning off the tool bar slow?

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#180]
According to `esup`, `(tool-bar-mode -1)` takes `0.155sec`. This is surprising, and suggests that there might be some room for optimization.

It has been suggested by @PythonNut that adding `Emacs*toolBar: 0` to `~/.Xresources` might improve the situation, since Emacs would not create the tool bar in the first place.

This is only relevant to windowed Emacs.

**Comment by anuragm** [comment]
Same can be done on OS X by using the commands 

`defaults write org.gnu.Emacs Emacs.toolBar -bool false`

and using a conditional in Emacs before turning off the toolbar mode

```lisp
(when tool-bar-mode
  (tool-bar-mode -1))
```

Shaves off about 20% of my Emacs start-up time, and tool bar is also turned off on a new computer where I haven't changed X or NS preferences.

**Comment by raxod502** [comment]
Unfortunately, this doesn't appear to work for me. I tried wrapping the call to `tool-bar-mode` in a conditional, using the `defaults write` command, adding

```
Emacs*toolBar: 0
emacs24.toolBar: 0
emacs25.toolBar: 0
Emacs.toolBar: 0
```

to my `~/.Xresources` as well as running `xrdb -merge ~/.Xresources`. Still takes 0.08s, mysteriously.

([Reference](http://emacs.stackexchange.com/q/9581/12534))

**Comment by matthewbauer** [comment]
I've had the same problem where ```defaults write``` doesn't work. Debugging a little, I can't find any notes on how this works within Emacs. Could this be a difference between ```emacs-ns``` and ```emacs-mac```? @anuragm which Emacs version are you running that reads from the defaults?

Emacs version:
```
GNU Emacs 25.2.1 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42))
 of 2017-05-29
```

**Comment by matthewbauer** [comment]
Ok, I've finally got it:

```
defaults write org.gnu.Emacs Emacs.ToolBar -string no
defaults write org.gnu.Emacs Emacs.ScrollBar -string no
```

"ToolBar " and "ScrollBar" need to be capitalized.

**Comment by raxod502** [comment]
@matthewbauer That's great, thanks for the advice. Since I don't use windowed Emacs on a regular basis, it'll probably be a while until I can check this out myself, but I can definitely believe the capitalization would make a difference.

**Comment by matthewbauer** [comment]
Actually it doesn't work for scroll bar for some reason but that is usually like <100ms for me.

**Comment by raxod502** [comment]
Man, I wish the specifics of the Emacs startup were properly customizable. It's embarrassing that there's still no way to specify a custom `.emacs.d` directory without re-setting `$HOME`.

**Comment by raxod502** [comment]
Well, this is interesting. Apparently the whole startup procedure is actually in Elisp, not C. It's all in 
`startup.el.gz`. So this can be properly debugged… maybe. Here's some relevant code:

#### Reading X properties and enabling tool-bar-mode

```
(defun x-apply-session-resources ()
  "Apply X resources which specify initial values for Emacs variables.
This is called from a window-system initialization function, such
as `x-initialize-window-system' for X, either at startup (prior
to reading the init file), or afterwards when the user first
opens a graphical frame.

This can set the values of `menu-bar-mode', `tool-bar-mode', and
`no-blinking-cursor', as well as the `cursor' face.  Changed
settings will be marked as \"CHANGED outside of Customize\"."
  (let ((no-vals  '("no" "off" "false" "0"))
	(settings '(("menuBar" "MenuBar" menu-bar-mode nil)
		    ("toolBar" "ToolBar" tool-bar-mode nil)
		    ("cursorBlink" "CursorBlink" no-blinking-cursor t))))
    (dolist (x settings)
      (if (member (x-get-resource (nth 0 x) (nth 1 x)) no-vals)
	  (set (nth 2 x) (nth 3 x)))))
  (let ((color (x-get-resource "cursorColor" "Foreground")))
    (when color
      (put 'cursor 'theme-face
	   `((changed ((t :background ,color)))))
      (put 'cursor 'face-modified t))))
```

#### Setting up tool bar during startup

```
  (when (fboundp 'x-create-frame)
    ;; Set up the tool-bar (even in tty frames, since Emacs might open a
    ;; graphical frame later).
    (unless noninteractive
      (tool-bar-setup)))
```

Note that this happens *before* loading the init file, so there's no hope of affecting it from that.

#### Calling x-apply-session-resources during startup

```
  ;; Make sure window system's init file was loaded in loadup.el if
  ;; using a window system.
  ;; Initialize the window-system only after processing the command-line
  ;; args so that -Q can influence this initialization.
  (condition-case error
    (unless noninteractive
      (if (and initial-window-system
	       (not (featurep
		     (intern
		      (concat (symbol-name initial-window-system) "-win")))))
	  (error "Unsupported window system `%s'" initial-window-system))
      ;; Process window-system specific command line parameters.
      (setq command-line-args
            (let ((window-system initial-window-system)) ;Hack attack!
              (handle-args-function command-line-args)))
      ;; Initialize the window system. (Open connection, etc.)
      (let ((window-system initial-window-system)) ;Hack attack!
        (window-system-initialization))
      (put initial-window-system 'window-system-initialized t))
    ;; If there was an error, print the error message and exit.
    (error
     (princ
      (if (eq (car error) 'error)
	  (apply 'concat (cdr error))
	(if (memq 'file-error (get (car error) 'error-conditions))
	    (format "%s: %s"
                    (nth 1 error)
                    (mapconcat (lambda (obj) (prin1-to-string obj t))
                               (cdr (cdr error)) ", "))
	  (format "%s: %s"
                  (get (car error) 'error-message)
                  (mapconcat (lambda (obj) (prin1-to-string obj t))
                             (cdr error) ", "))))
      'external-debugging-output)
     (terpri 'external-debugging-output)
     (setq initial-window-system nil)
     (kill-emacs)))
```

The important part being `window-system-initialization`, which is a `cl-defgeneric` that delegates to various `term/` implementations that in turn call `x-apply-session-resources`. The above code happens before calling `tool-bar-setup`.

#### Conclusion

I don't have one. Just food for thought.

**Comment by matthewbauer** [comment]
Correction, the command that works are actually:

```
defaults write org.gnu.Emacs ToolBar -string no
defaults write org.gnu.Emacs ScrollBar -string no
```

**Comment by raxod502** [comment]
Depending on how the `package.el` discussion on emacs-devel goes, we might be able to pre-empt the tool bar directly from the init-file! (At least in Emacs 26.)

https://lists.gnu.org/archive/html/emacs-devel/2017-08/msg00608.html

> ```
> BTW, here's another idea:
> - use a separate "early-config" file.  Now, you probably wonder why
>   I say it's "another" idea, so here's the reason: this file would be
>   loaded before the initial GUI frame is created (so it would solve
>   another similar problem at the same time, which is "how do I turn OFF
>   those GUI elements in my .emacs such that they never show up, not even
>   temporarily while we process the .emacs").
> ```

**Comment by AmaiKinono** [comment]
[Here](https://emacs.stackexchange.com/a/32661)'s what I found today, using

``` emacs-lisp
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(menu-bar-lines . 0) default-frame-alist)
```

rather than the regular way. This does save me 0.1 or 0.2 seconds, but unfortunately one can't do the same with scroll-bar-mode, which takes up another 0.1 seconds.

**Comment by raxod502** [comment]
Implemented in https://github.com/raxod502/radian/commit/f1c0733df0de736e3f2dfefda422623c366e805d.

**Comment by AmaiKinono** [comment]
I just found that vyp referenced this issue in [a commit](https://github.com/vyp/dots/commit/b617f991ff5ece114ce20018481ee010e9f5420f), where he did this:

``` emacs-lisp
(push '(vertical-scroll-bars) default-frame-alist)
```

It's in `early-init.el`. Since I still use Emacs 26 I put this in my `init.el`, and it works, saving another 0.1 seconds. You can also do:

``` emacs-lisp
(push '(vertical-scroll-bars . nil) default-frame-alist)
```

which is the same.

**Comment by raxod502** [comment]
I believe this issue has been solved for Radian since we now do literally all of init in the early init-file under Emacs 27.
