### ISSUE TITLE
Better flx sorting in Ivy

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#189]
We should be getting `flx` sorting in our non-`counsel-M-x` completions. Instead, we're apparently getting *alphabetical* sorting. This is highly problematic.

**Comment by raxod502** [comment]
This is due to `ivy-flx-limit`, which has been increased on the `wip` branch. A better solution based on @PythonNut's code [here](https://github.com/abo-abo/swiper/issues/207#issuecomment-140439385) is pending.

**Comment by PythonNut** [comment]
Well, maybe more like [this code](https://github.com/abo-abo/swiper/issues/207#issuecomment-143516630)

**Comment by raxod502** [comment]
Right @PythonNut, but I wanted to link to a comment which would give good context on the issue and approach.

**Comment by raxod502** [comment]
Resolved in https://github.com/abo-abo/swiper/pull/843.
