### ISSUE TITLE
I want jump-to-definition for C/C++

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#243]
Perhaps this can be provided by Semantic, as Irony [does not seem to support it yet](https://github.com/Sarcasm/irony-mode/issues/161).

**Comment by PythonNut** [comment]
My success with Semantic for C/C++ navigation has been extremely limited, if not nonexistent. Perhaps I'm doing something wrong, but I'm not convinced Semantic can handle C/C++ projects of any reasonable complexity.

**Comment by raxod502** [comment]
I'm actually leaning toward something like https://github.com/raxod502/radian/issues/285 these days, because despite how wonderful of an idea semantically-aware code navigation seems like, it never seems to work out so nicely in practice.

**Comment by PythonNut** [comment]
I can confirm that semantic systems that work really, really well do exist (i.e. Visual Studio, JetBrains, etc.) but we don't seem to have them for Emacs.

`dumb-jump` does seem to work decently well, but of course it's pretty dumb and if you have multiple things with the same name in a project it starts falling down.

**Comment by raxod502** [comment]
Implemented with LSP via clangd. Works like a charm.
