### ISSUE TITLE
Flycheck errors for JSON

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#318]
Spurious warning messages:

```
Suspicious state from syntax checker json-python-json: Flycheck checker json-python-json returned non-zero exit code 1, but its output contained no errors: No JSON object could be decoded

Try installing a more recent version of json-python-json, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by steinarb** [comment]
I get these too

My versions of everything: debian 9.6 "stretch", amd64, emacs 25.1 (25.1+1-4+deb9u1), flycheck 31 (from melpa stable).

**Comment by wouterbeek** [comment]
I have this issue too.  The annoying thing is that there is no easy to find package in pip or on the Internet that is called `json-python-json`.

**Comment by raxod502** [comment]
It's not a package. Flycheck is using the `json` module in the Python standard library. The warning message is automatically generated based on the syntax checker name, which is always the language followed by the tool name (`python -m json`). Upgrading will not fix the issue; it is a problem with Flycheck.

**Comment by raxod502** [comment]
It finally annoyed me too much

**Comment by raxod502** [comment]
Okay, I did it properly this time. I think.
