### ISSUE TITLE
python -- identifies splat operator as syntax error

### ISSUE THREAD

**Issue by redpanda1234** [raxod502/radian#350]
Example:

coord = [0,0,0] 
x, y, z = *coord 

Here, the second line is flagged as a syntax error.

**Comment by raxod502** [comment]
This is because the right-hand side of a multiple assignment statement takes an actual tuple instead of multiple arguments. In this case, you want

```
coord = [0, 0, 0]
x, y, z = coord
```

The syntax error happens just the case in a REPL for Python 2 or Python 3.

**Comment by redpanda1234** [comment]
Oops.  How embarrassing.
