### ISSUE TITLE
Disable indent-tabs-mode in makefile-mode without breaking existing tabs

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#351]
WHY?!!??!??!??!!11?!??!11/!!1

**Comment by redpanda1234** [comment]
Rest in peace.

**Comment by raxod502** [comment]
Sad. It turns out that disabling `indent-tabs-mode` causes tabs to magically get converted into spaces when typing things after them, which makes no sense. So we need to fix the problem in a different way.

**Comment by raxod502** [comment]
Or we could not do this.
