### ISSUE TITLE
Cannot type over ending $$ in AUCTeX with Smartparens

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#382]
Given

```
Let $E = mc^2|$
```

with point at `|`, typing `$` should move point to the right, not insert another pair of `$$`.

Granted this didn't work with `electric-pair-mode` (I think?) so this isn't as disappointing. But I'm pretty sure Smartparens is capable of dealing with this.

**Comment by redpanda1234** [comment]
bump

**Comment by redpanda1234** [comment]
Also, perhaps prefacing `$` with a `\` should automatically remove the second `$`. Obviously if the first is being escaped, we're not using it for math mode.

**Comment by raxod502** [comment]
In the latest version, it appears to me that it's impossible to type a dollar sign of any description inside math mode. See #401.

**Comment by raxod502** [comment]
This works now, as long as point doesn't leave the sexp entirely.

@redpanda1234, open a new issue for your other concern.
