### ISSUE TITLE
add `org-version` function for elfeed compatibility

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [raxod502/radian#393]
Hi
I've used your hack for overriding emacs's tendency to use its built in org-mode instead of the latest release. It works pretty well. One thing I found though is that an error comes about with the [`Elfeed`](https://github.com/skeeto/elfeed) emacs package because it used the function `(org-version)` in its [`elfeed-link.el`](https://github.com/skeeto/elfeed/blob/master/elfeed-link.el) file. `org-version` returns  "N/A" with the hack. Elfeed expects a string that can convert it to a number. `(version< (org-version) "9.0")`.
This is easily fixed with a `(defun org-version () "9.1.3")`. Just wanted to recommend this in case you or anyone who used this hacks uses packages like `elfeed` that call `(org-version)`.

**Comment by raxod502** [comment]
This will be fixed (by virtue of the hack no longer being necessary) when https://github.com/raxod502/straight.el/issues/72 and https://github.com/raxod502/straight.el/issues/115 are closed. Thanks for the report. I'm happy to accept a pull request patching Radian in the meantime.
