### ISSUE TITLE
Projectile appears not to clear out project paths that no longer exist?

### ISSUE THREAD

**Issue by redpanda1234** [raxod502/radian#398]
E.g., if you move a project to a new directory, projectile won't remove it from tab completion. This seems that it could be checked periodically? 

How best to address without adding large overhead to startup ?

**Comment by raxod502** [comment]
Projectile has a command for removing nonexistent projects. If you don't want to run it manually, I would recommend investigating package `midnight`, which is bundled with Emacs. It's designed for this sort of thing (running commands periodically).

**Comment by redpanda1234** [comment]
This appears to be a good solution. Maybe I'll look into it next week.
