### ISSUE TITLE
ad-handle-definition: 'LaTeX-add-bibliographies' got redefined

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#402]
Message shown when enabling `latex-mode` directly after Emacs init.

**Comment by jhenahan** [comment]
Relevant: https://andrewjamesjohnson.com/suppressing-ad-handle-definition-warnings-in-emacs/

Looks like this is largely just noise generated by defadvice, and can be silenced by setting

    (setq ad-redefinition-action 'accept)

**Comment by raxod502** [comment]
Yes, I have seen this before. I have tended to avoid it in the past, since I assumed the warning (i.e. a function definition was discarded due to delayed activation of advice) was indicating a real problem. If I keep running into this, though, I will probably just silence the warnings (possibly after reporting bugs upstream).

**Comment by raxod502** [comment]
Solved by doing as @jhenahan suggested.
