### ISSUE TITLE
consider "(load"-ing autoloads

### ISSUE THREAD

**Issue by holgerschurig** [raxod502/radian#405]
Currently straight.el is creating FOO-autoloads.el files that "(provide FOO-autoloads)" themselves. And I gess they get loaded with "(require FOO-autoloads").

However, this inflates the variable "features", it's now much harder to see which modules are actually loaded than before. BTW, package.el doesn't do this either.

I actually think that autoload files never depend on each other, so there is no need to "(require" them. Instead, you can simply (load "FOO-autoloads") them, or?

**Comment by raxod502** [comment]
Can you file this issue against `straight.el` instead?

**Comment by holgerschurig** [comment]
Oops, sorry.
