### ISSUE TITLE
git-credential-cache doesn't always work with graphical Emacs

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#408]
Under some circumstances, I am prompted for my password every time.

**Comment by peschkaj** [comment]
I am able to reproduce this across several boots of macOS as well as restarting emacs several times per boot. Is there any sort of workaround for this?

**Comment by raxod502** [comment]
Sorry, I stopped using HTTPS for Git a long time ago, and hence I stopped encountering this problem. If you figure out what the issue is, however, I'd gladly install the fix into Radian.

**Comment by peschkaj** [comment]
Oh, apologies - this is occurring with an SSH git repository. I've posted on the [emacs stackexchange](https://emacs.stackexchange.com/questions/44412/emacs-prompting-for-github-password) and I'm attempting to get to a solution. But, from your comment, it sounds like my current problem is not the problem you had.

**Comment by raxod502** [comment]
I see from the linked thread that you figured this out. Yes, sorry, I forgot that magit-gh-pulls requires initial setup via HTTPS. (I have my `~/.gitconfig.local` under version control so it was truly a one-time setup for me.) This is completely unrelated to git-credential-cache, which only applies to remote operations over HTTPS.

That said, I feel like magit-gh-pulls should not be prompting you for anything unless you run `# g` or a similar command. This is probably worth opening a new issue for.

**Comment by raxod502** [comment]
Cannot reproduce.
