### ISSUE TITLE
Setting ffap-url-regexp nil breaks visiting #+INCLUDE files with C-c '

### ISSUE THREAD

**Issue by jhenahan** [raxod502/radian#409]
https://github.com/raxod502/radian/blob/10576980f4a202fbb4e1d61696fcde69f1c9fc8a/radian-emacs/radian-find-file.el#L441

Took me ages to figure out why `C-c '` wasn't working with some of the configuration I've been using from Radian. 😆 

I'll see if I can figure out a solution unless you know one immediately.

Also, reading Radian has changed my whole style of Emacs configuration for the better, so I appreciate all your hard work.

**Comment by raxod502** [comment]
Ah, sorry but what exactly is `C-c '` supposed to do? It's not bound in Radian, at least in any of the modes I tried.

My hunch would be that this is a bug in some other package, since `ffap` explicitly documents that you can set `ffap-url-regexp` to nil in order to disable URL matching.

**Comment by jhenahan** [comment]
It's =org-edit-special=, which does everything from editing code blocks to visiting links in Org files. In particular, the issue here arises with how Org decides whether or not a link to visit is a URL or a file. If =ffap-url-regexp= is set nil, it causes an error and fails to visit the file. I think the fix is probably to send it up the chain to the Org maintainers and see if there's a better way to handle that, I just wanted to bring it up in case anyone else uses parts of your config and hits the same edge case I did.

**Comment by raxod502** [comment]
Yes, sounds like an Org bug. I would be happy to accept an advice or `el-patch` for Radian which fixes the problem in `org-edit-special`. (Although I guess the real problem is `org-file-url-p`.)

**Comment by raxod502** [comment]
Solved, I guess, since we no longer use `ffap` :)
