### ISSUE TITLE
Make radian-path.el load ~/.profile instead of using path_helper

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#412]

**Comment by jhenahan** [comment]
I've also had very good results with [`exec-path-from-shell`](https://github.com/purcell/exec-path-from-shell) in my config.

**Comment by raxod502** [comment]
@jhenahan Yes, I may implement this feature using `exec-path-from-shell`. (But it might just be easier to do it myself.) Thanks for the suggestion.
