### ISSUE TITLE
Process to load a different theme

### ISSUE THREAD

**Issue by peschkaj** [raxod502/radian#433]
While `zerodark` is a nice theme, I prefer a different theme. To load a different theme, I understand that I need to set `radian-color-theme-enable` to `nil`, but I'm unclear on where this should occur in `init.local.el`.

What is the process for loading a custom theme on startup?

**Comment by raxod502** [comment]
`init.local.el` is loaded [at the beginning of `radian.el`](https://github.com/raxod502/radian/blob/19416a80de662ee8bb235caf071d2147e74e5ce9/emacs/radian.el#L175). Then if `radian-color-theme-enable` is non-nil, the color theme is loaded [at the end of `radian.el`](https://github.com/raxod502/radian/blob/19416a80de662ee8bb235caf071d2147e74e5ce9/emacs/radian.el#L4872-L4877). In between these two points, [`radian-after-init-hook` is run](https://github.com/raxod502/radian/blob/19416a80de662ee8bb235caf071d2147e74e5ce9/emacs/radian.el#L4857). However, note that if you wish for `zerodark-theme` to not be installed, you should disable `radian-color-theme-enable` before [that happens](https://github.com/raxod502/radian/blob/19416a80de662ee8bb235caf071d2147e74e5ce9/emacs/radian.el#L4852-L4853).

Thus,

```elisp
(setq radian-color-theme-enable nil)

(defun radian-local--after-init ()
  (load-theme 'leuven))
```

or whatever (you can install your own color theme package if needed).

Let me know if you have further questions.
