### ISSUE TITLE
Issues on windows

### ISSUE THREAD

**Issue by Whil-** [raxod502/radian#457]
Hi!

Nice to see how you've configured your plugins into a ready to go Emacs! I realize it has not been configured for Windows though, but still thought of registering this issue. Do with it what you like!

So, this is my log in emacs after initially managing to install this radian package in windows:
```
$ cd "c:/Users/gusta/"
$ "find" "/dev/null" "-newermt" "2018-01-01 12:00:00"

FIND: Invalid switch

[Return code: 2]

$ cd "c:/Users/gusta/"
$ "touch" "-d" "2020-06-15 14:24:25" "c:/Users/gusta/.emacs.d/straight/mtimes/2020-06-15 14:24:25"

[File error while searching for program]
```

the `FIND: Invalid switch` ofc. is because it looks for the windows-version of find. I have configured this in init.local.el already though:
(setq straight-find-executable (expand-file-name "C:/msys64/usr/bin/find.exe"))
So a bit surprising with that error. Maybe find is used to early in the init-process?

Second error is due to touch not being available on Windows. Haven't found a workaround for that yet, except adding msys64/usr/bin to $path. Something I'd rather avoid.

Best
Gustav

**Comment by Whil-** [comment]
Oh, should mention that the code above is from *straight-process*.

**Comment by meziberry** [comment]
Maybe you can change the windows OS env  to make sure the msys2 prior to OS.

**Comment by raxod502** [comment]
In fact, you've found a bug. I was not respecting the value of `straight-find-executable` for that particular `find` command. Try with the latest commit :)

**Comment by raxod502** [comment]
Regarding your second concern, would it be good enough if there were a `straight-touch-executable` user option which you could customize?

**Comment by raxod502** [comment]
To be clear, by the way, you'll need to go into `~/.emacs.d/straight/repos/straight.el` or its equivalent on Windows and then pull, since I have not pushed an update to Radian.

**Comment by Whil-** [comment]
> In fact, you've found a bug. I was not respecting the value of `straight-find-executable` for that particular `find` command. Try with the latest commit :)

Great, will try it out. Side-question; Any reason for not using `find-program` and creating a separate variable for straight?

> Regarding your second concern, would it be good enough if there were a `straight-touch-executable` user option which you could customize?

Yes, that sounds resonable

> To be clear, by the way, you'll need to go into `~/.emacs.d/straight/repos/straight.el` or its equivalent on Windows and then pull, since I have not pushed an update to Radian.

Got it.

**Comment by Whil-** [comment]
Since the name for this issue is kind of broad I'll take the opportunity to raise another concern. And it relates to the compilation process that is set up. This also breaks on windows. Relying on make and bash-scripts for compilation as is done in `radian-byte-compile` will break in 99% of windows users configurations. Either it should only be active on non-windows machines or some kind of conditional logic is needed to determine how to do the external compilation.

Regards.

**Comment by raxod502** [comment]
Your point is fair. You should open a new issue just for that, so that others may easily find it and perhaps contribute a solution.
