### ISSUE TITLE
exec-path setting is wrong on windows+msys2

### ISSUE THREAD

**Issue by meziberry** [raxod502/radian#460]
exec-path is set differently under the following two scenes. 

- when starting emacs from `cmd` or `powershell`. exec-path looks like this:

**wrong** `("c:./c/msys/mingw64/bin:/c/msys/usr/local/bin:/c/msys/usr/bin:/c/msys/usr/bin: ......")`

-  when starting emacs from `msys bash` or `msys zsh`. exec-path looks like this:

**right** `("c:/msys/mingw64/bin/" "c:/msys/usr/local/bin/" "c:/msys/usr/bin/" "c:/msys/usr/bin/" ......)`

Environment
`win10 + msys2`  `python3 ported on msys2`

I noticed that exec-path is set in `radian-env-setup` through `scripts/print_env.py`.  so i ran the `os.environ.items` on cmd and zsh shell.
I get environment variable `PATH` style is different. 
One is `/c/msys/mingw64/bin:/c/msys/usr/local/bin:/c/msys/usr/bin:/c/msys/usr/bin:` style. 
Another is `C:\\msys\\mingw64\\bin;C:\\msys\\usr\\local\\bin;C:\\msys\\usr\\bin;C:\\msys\\usr\\bin;` style.
Maybe this bring the exec-path can't set rightly. but i don't why, and how to correct it.

Finally, I like radian and CTRLF.  thank you.

**Comment by meziberry** [comment]
I find that the reason is  shell' PATH directory order is different. When i use this order`/c/msys/mingw64/bin:/c/msys/usr/local/bin:/c/msys/usr/bin:`. exec-path can be set correctly. 
This issue is closer to msys2. so i close it.  Thank you.

**Comment by meziberry** [comment]
On msys2， Python from `mingw64/bin` is windows native application, the one from`/usr/bin` is UNIX emulated application.

**Comment by raxod502** [comment]
Sounds good, glad you figured it out :)
