### ISSUE TITLE
Error trying out emacs configuration

### ISSUE THREAD

**Issue by albertsj1** [raxod502/radian#472]
Hi.  I thought I'd try out your emacs configuration and I'm getting an error message.

```bash
Warning (initialization): An error occurred while loading ‘/Users/johnalb/.emacs.d/early-init.el’:
File is missing: Opening input file, No such file or directory, /Users/johnalb/.emacs.d/straight/repos/emacsmirror-mirror/mirror
```

What I've done at this point is:  (I'm on a mac)

1. Cloned the radian repo to a directory under my home directory
2. create a new ~/.emacs.d directory.
3. Per the readme, symlink'd ./emacs/init.el => ~/.emacs.d/init.el, ./emacs/early-init.el => ~/.emacs.d/early-init.el, ./emacs/versions.el => ~/.emacs.d/straight/versions/radian.el

From the error message, it seemed like `~/.emacs.d/straight/repos` directory was also needed, so I created it, but that didn't help.

**Comment by albertsj1** [comment]
I tried again today and everything worked after it finished downloading every.  So maybe there was a temporary network issue?  I didn't change the configuration at all, so not sure.  🤷‍♂️ 
Thank you for your work on this and providing it to the public.

**Comment by raxod502** [comment]
That's very odd. Glad you got it working! It seems like somehow the Emacsmirror recipe repository was not cloned completely, although it's unclear how that's possible since Git generally deletes a repository when it fails to finish cloning.
