### ISSUE TITLE
bootstrap-file should respect straight-base-dir

### ISSUE THREAD

**Issue by haji-ali** [raxod502/radian#473]
I believe this definition

https://github.com/raxod502/radian/blob/3ae994990f6757d91e4b900a72e5541cc31b4318/emacs/radian.el#L508-L510

Should use `straight-base-dir` when non-nil instead of `user-emacs-directory`. Perhaps something like this

```lisp
(expand-file-name
        "straight/repos/straight.el/bootstrap.el"
       (or (bound-and-true-p straight-base-dir)
            user-emacs-directory))
```

**Comment by raxod502** [comment]
Yep, sounds about right. I've applied that fix to `develop`, thanks for pointing it out!
