### ISSUE TITLE
Disable ctrl-f bindings in the minibuffer

### ISSUE THREAD

**Issue by haji-ali** [raxod502/radian#476]
I use `selectrum` for minibuffer completion and so I rarely need to search for a string in the minibuffer. I would like to disable ctrlf bindings there (to use the key sequences for more useful commands, in that context). 

Is this possible at all? In particular, it seems that ctrlf bindings override local ones. This might be related to raxod502/ctrlf#62 and raxod502/ctrlf#64, but I am not sure.

**Comment by raxod502** [comment]
This is probably a Radian bug, then, so I'll transfer the issue. Radian may have still been on an old commit of CTRLF. I've pushed a new commit to `develop` updating the lockfile to the latest version of CTRLF. Try now? (`M-x straight-thaw-versions`)

**Comment by haji-ali** [comment]
Updating worked and remapping `C-s` is now possible!
As a plus, when I don't override it, pressing `C-s` now searches the active buffer instead of the minibuffer.
