### ISSUE TITLE
How to use ox-confluence?

### ISSUE THREAD

**Issue by albertsj1** [raxod502/radian#477]
Hi. I'm trying to figure out how to enable and use ox-confluence. 
According to [the org manual](https://orgmode.org/worg/exporters/ox-overview.html), it should be in the org contrib directory, but the clone I have of org that radian created doesn't have a contrib directory.  I saw in issue #442 the suggestion was to add `(straight-use-package 'org-plus-contrib)`, but that gives me this error message.
```
Building org...done
Failed to byte-compile: Building org not allowed in safe mode
```

Any help appreciated.
Thanks

**Comment by raxod502** [comment]
The configuration for this was wildly out of date. I've fixed it up and added a new user option, `radian-org-enable-contrib`, which you can set to non-nil in `init.local.el` in order to get everything working. Let me know if that works for you!

**Comment by albertsj1** [comment]
Works perfectly.  Thank you.
