### ISSUE TITLE
radian-scroll-up command breaks mouse-wheel-follow-mouse

### ISSUE THREAD

**Issue by hrehfeld** [raxod502/radian#486]
`(setq mouse-wheel-follow-mouse t)`, use mouse in inactive window. Active window scrolls.

**Comment by raxod502** [comment]
I observe that behavior too, but if your Emacs is running in terminal mode, how would it know where your mouse cursor is in the first place? With `emacs -Q`, you get the same behavior, but it doesn't even scroll, it just moves point vertically.

**Comment by hrehfeld** [comment]
hmm, no idea about terminal usage, but this happens to me on in `display-graphic-p`.

**Comment by raxod502** [comment]
That's very odd. What operating system / distro / window manager are you using?

**Comment by hrehfeld** [comment]
Archlinux & X11 with xmonad, regularly updated.

**Comment by hrehfeld** [comment]
Hmm, this doesn't happen right now, inactive window scrolls, so I'm closing for now. Thanks for looking into it!
