### ISSUE TITLE
Patches without changes?

### ISSUE THREAD

**Issue by haji-ali** [raxod502/radian#503]
There is some strange code in `radian.el` that I am trying to understand. In `json-mode` and `osx-trash`, there are several definitions under `:init/el-patch` that don't contain any `el-patch-*` forms and that are seemingly identical to the original definitions. Is this right?

**Comment by raxod502** [comment]
Yep, these are used for lazy-loading: https://github.com/raxod502/el-patch#lazy-loading-packages
